In [4]:
import pandas as pd
new_data = pd.read_csv("data/updated_counts_avg_max_severity_dataset.csv")
original_data = pd.read_csv("data/updated_counts_severity_dataset.csv")

In [5]:
original_data.head()

,artist_all,artist_base,rank,song,year,artist_featured,song_clean,artist_clean,lyrics,acousticness,...,profanity_content_count,profanity_avg_severity,mental_slurs_content_count,mental_slurs_avg_severity,religious_slurs_content_count,religious_slurs_avg_severity,racial_slurs_content_count,racial_slurs_avg_severity,sexual_content_content_count,sexual_content_avg_severity
0,the isley brothers,the isley brothers,27.0,fight the power,1975.0,NaN,fight the power,the isley brothers,time is truly wastin theres no guarantee yeah ...,0.061900,...,10,0.198956,25,0.059527,0,0.0,1,0.012325,5,0.397302
1,prince and the revolution,prince and the revolution,21.0,let's go crazy,1984.0,NaN,lets go crazy,prince and the revolution,dearly beloved we are gathered here today to ...,0.019200,...,20,0.126944,63,0.176559,0,0.0,7,0.119137,38,0.097181
2,emf,emf,6.0,unbelievable,1991.0,NaN,unbelievable,emf,you burden me with your questions youd have m...,0.000341,...,23,0.003310,40,0.073247,0,0.0,6,0.209042,13,0.017500
3,tesla,tesla,73.0,signs,1991.0,NaN,signs,tesla,and the sign says long hair freaky people need...,0.035000,...,24,0.180956,55,0.098419,0,0.0,2,0.024315,15,0.295285
4,sir mix-a-lot,sir mix-a-lot,2.0,baby got back,1992.0,NaN,baby got back,sir mix a lot,oh my god becky look at her butt it is so big...,0.003910,...,42,0.302159,98,0.070974,0,0.0,9,0.164474,24,0.141296

In [6]:
new_data.head()

,lyrics,acousticness,danceability,energy,instrumentalness,loudness,speechiness,tempo,valence,explicit,...,mental_slurs_max_severity,religious_slurs_content_count,religious_slurs_avg_severity,religious_slurs_max_severity,racial_slurs_content_count,racial_slurs_avg_severity,racial_slurs_max_severity,sexual_content_content_count,sexual_content_avg_severity,sexual_content_max_severity
0,I see it in your eyes You're seconds from dest...,0.28800,0.466,0.585,0.000000,-5.347,0.0432,126.054,0.289,False,...,0.254769,0,0.0,0.0,0,0.000000,0.000000,15,0.021820,0.189041
1,Master P: (Chorus)(3X) Mama always told me (to...,0.02020,0.692,0.551,0.000000,-8.252,0.2480,163.932,0.333,True,...,0.994731,0,0.0,0.0,34,0.636528,0.994731,57,0.160300,0.994731
2,"If I told you, that this couldn't get better b...",0.00262,0.725,0.874,0.000412,-3.715,0.0396,127.985,0.748,False,...,0.230569,0,0.0,0.0,0,0.000000,0.000000,28,0.027643,0.230569
3,I feel your love I feel time is up When I was ...,0.74700,0.732,0.408,0.000229,-8.475,0.0360,87.016,0.663,False,...,0.263980,0,0.0,0.0,1,0.000876,0.000876,24,0.008998,0.039755
4,Don't know when it started and I don't know wh...,0.00306,0.871,0.531,0.213000,-9.373,0.0473,123.978,0.618,False,...,0.189041,0,0.0,0.0,0,0.000000,0.000000,44,0.024825,0.189041

In [9]:
import torch
trans_model = torch.load("transformer_model.pth")

C:\Users\ziyue\AppData\Local\Temp\ipykernel_25988\1671887894.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  trans_model = torch.load("transformer_model.pth")

AttributeError: Can't get attribute 'SongExplicitnessModel' on <module '__main__'>